### ISSUE TITLE
Pass extra arguments to `ColumnDataSource` for more customized tooltips

### ISSUE THREAD

**Issue by slochower** [SimonBoothroyd/plotmol#5]
It would be great to expose other sources of data that get passed to `ColumnDataSource` like some sort of molecule title, so that a custom `tooltip_template` could take advantage of them.

https://github.com/SimonBoothroyd/plotmol/blob/19a0aa890a0d9a597080bf7d751bcb8146117548/plotmol/plotmol.py#L103

```python
def custom_tooltip_template() -> str:
    """Returns the a custom html based template to use for the figure hover pop-up with the molecule image and name."""

    return """
    <div>
        <div>
            <img src="@image" ></img>
        </div>
        <div>
            <span style="font-size: 10px; color: #696;">$molecule_name</span>
        </div>

    </div>
"""
```

**Comment by SimonBoothroyd** [comment]
I agree this would definitely be nice to expose! @slochower I added a `custom_column_data` argument to `scatter` in #7 - does this work for you?

**Comment by slochower** [comment]
This is perfect. 🎉
